### ISSUE TITLE
Validate token expiration

### ISSUE THREAD

**Issue by viklund** [neicnordic/sda-s3proxy#322]
Tokens that have expired should not be able to upload.

- [x] Test that the tokens are unusable after expiration
- [ ] Deploy the new version before the BP meeting

**Comment by norling** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Giant-Sloth-6041ec3fd9297d0016321f73/issues/neicnordic/sda-s3proxy/322?planning-poker) with Zenhub @aaperis @dbampalikis @jbygdell @kostas-kou @viklund
